project/blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.EntryListView.as_view(), name='entry_list'),

    url(r'^(?P<page>\d+)$', views.EntryListView.as_view(), name='entry_list'),

    url(r'^latest\.xml$', feeds.EntryFeed(), name='entry_feed'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<slug>[\w-]+)$',
        views.EntryDetailView.as_view(), name='entry_detail'),

]

urlpatterns = [url(r'^', include(urls, namespace='blog'))]

project/members/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.conf.urls import include, url
from django.contrib.auth.decorators import permission_required

from . import views

MEMBERS_PERMISSION_REQUIRED = 'members.can_change_member'


urls = [

    url(r'^new/',
        views.member_create_view,
        name='member_form'),

    url(r'^success/',
        views.TemporaryMemberSuccessView.as_view(),
        name='temporarymember_success_view'),

    url(r'^approve/',
        permission_required(MEMBERS_PERMISSION_REQUIRED)(
            views.member_approval_view,
        ),
        name='member_approval'),

    url(r'^import/$',
        permission_required(MEMBERS_PERMISSION_REQUIRED)(
            views.import_view
        ),
        name='members_import'),

    url(r'^list/$',
        permission_required(MEMBERS_PERMISSION_REQUIRED)(
            views.MemberListView.as_view(),
        ),
        name='member_list'),

    url(r'^\+/(?P<number>\d+)$',
        views.member_detail_view,
        name='member_detail'),

]

urlpatterns = [url(r'^', include(urls, namespace='members'))]

project/menus/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.MenuTypeListView.as_view(), name='menutype_list'),

    url(r'^(?P<page>\d+)$', views.MenuTypeListView.as_view(), name='menutype_list'),

    url(r'^latest\.xml$', feeds.MenuFeed(), name='menu_feed'),
]

urlpatterns = [url(r'^', include(urls, namespace='menus'))]

project/site/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.HomepageDetailView.as_view(), name='homepage_detail'),

]


urlpatterns = [url(r'^', include(urls, namespace='site'))]

project/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from debug_toolbar import urls as debug_toolbar_urls
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from project.sitemaps import sitemaps


urlpatterns = [

    # Site
    url(r'^', include('project.site.urls')),

    # Blog
    url(r'^blog/', include('project.blog.urls')),

    # Menu
    url(r'^menus/', include('project.menus.urls')),

    # Games Library
    url(r'^games/', include('project.library.urls')),

    # Bookings
    url(r'^bookings/', include('project.bookings.urls')),

    # Members
    url(r'^members/', include('project.members.urls')),

    # Robots
    url(r'^robots\.txt', include('robots.urls')),

    # XML Sitemap
    url(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # Admin Docs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # TinyMCE
    url(r'^tinymce/', include('tinymce.urls')),

]


if settings.DEBUG:
    # Only serve media files if in a development environment
    from django.conf.urls.static import static
    from django.views.generic import TemplateView

    urlpatterns += [
        url(r'^errors/404$', TemplateView.as_view(template_name='404.html')),
        url(r'^errors/500$', TemplateView.as_view(template_name='500.html')),
        url(r'^__debug__/', include(debug_toolbar_urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/members/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from datetime import date, timedelta
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives, send_mail
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django_date_extensions.fields import ApproximateDateField

from project.utils import get_current_site, generate_unique_hex
from . import querysets, settings


    # ApproximateDate(
    #     blank=True, null=True,
    #     help_text="We don't like having to ask for this but we children members are differently categorised. Only year, or month and year are required.")  # noqa

@python_2_unicode_compatible
class Member(models.Model):

    # If multiple users: consolidate
    # @@TODO: switch off blank/null=True, ensure users exist or are generated
    user = models.ForeignKey('auth.User', blank=True, null=True)

    number = models.PositiveIntegerField(unique=True)

    name = models.CharField(max_length=200, blank=True, default='',
                            verbose_name='Full Name',
                            )

    sort_name = models.CharField(max_length=200, blank=True, default='',
                                 verbose_name='Surname')

    ref_name = models.CharField(max_length=200, blank=True, default='',
                                verbose_name='First Name',
                                )

    title = models.CharField(max_length=64, blank=True, default='')

    notes = models.TextField(blank=True, default='')

    private_notes = models.TextField(blank=True, default='')

    emails = models.ManyToManyField('rolodex.Email', blank=True)

    phones = models.ManyToManyField('rolodex.Phone', blank=True)

    address = models.TextField(blank=True, default='')

    postcode = models.CharField(max_length=16, blank=True, default='')

    suburb = models.CharField(max_length=64, blank=True, default='')

    state = models.CharField(max_length=64, blank=True, default='')

    country = models.CharField(max_length=16, blank=True, default='Australia')

    year = models.PositiveIntegerField(blank=True, null=False, default=0)

    dob = models.DateField(
        blank=True, null=True,
        verbose_name='Birth date',
        help_text="Kept private.")
    #dob = ApproximateDateField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True, editable=True)

    updated_at = models.DateTimeField(auto_now=True, editable=False)

    # Redundant, but may be useful later as memberships are based upon days.
    # Potential efficiency can be found here by doing cron.
    is_current = models.BooleanField(db_index=True, default=True)

    key = models.CharField(max_length=64, blank=True, default='')
    legacy_source = models.CharField(max_length=64, blank=True, default='')

    site = models.ForeignKey('sites.Site', default=get_current_site,
                             related_name='members_member',
                             on_delete=models.PROTECT)

    objects = querysets.MemberQuerySet.as_manager()

    def __str__(self):
        string = ""
        string = "#{num} {name}".format(
            num=self.number, name=self.name)
        if self.is_active:
            return string + " (active)"
        return string

    @models.permalink
    def get_absolute_url(self):
        return ('members:member_detail', (), {'number': self.number})

    def get_emails(self):
        return ", ".join([email.email for email in self.emails.all()])

    def get_phones(self):
        return ", ".join([phone.phone for phone in self.phones.all()])

    def get_memberships(self):
        return ", ".join(
            ["{}".format(member.valid_from)
             for member in self.membership_set.all()])

    def save(self, *args, **kwargs):

        if not self.key:
            self.key = generate_unique_hex(
                length=16, hex_field='key',
                queryset=Member.objects.all())

        if not self.number:
            try:
                self.number = Member.objects.order_by('-number')[0].number + 1
            except IndexError:
                self.number = 1

        if not self.name:
            self.name = "{} {}".format(self.ref_name, self.sort_name)

        if not self.user:
            try:
                user = User.objects.get(username=self.number)
            except:
                user = User.objects.create_user(username=self.number)
                user.first_name = self.ref_name
                user.last_name = self.sort_name
                user.save()
            self.user = user

        super(Member, self).save(*args, **kwargs)

    def is_active(self):
        if self.membership_set.active():
            return True
        else:
            return False

    def send_welcome_email(self):
        subject, from_email, to = 'hello', 'from@example.com', 'to@example.com'
        text_content = 'This is an important message.'
        html_content = '<p>This is an <strong>important</strong> message.</p>'

        message = """Thank you for becoming a Guild member """
        subject = """Thank you for becoming a Guild member """
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.FROM_EMAIL,
            recipient_list=settings.TO_EMAILS,
        )

        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        return True


class Membership(models.Model):

    member = models.ForeignKey('members.Member')

    member_type = models.CharField(max_length=255,
                                   choices=settings.MEMBERS_TYPES)

    special = models.CharField(max_length=255, blank=True, default='')

    valid_from = models.DateField()

    valid_until = models.DateField(
        null=True, blank=False,
        help_text="""As the first day of the month following expiry. Eg. Nov 2018 = '1-Dec-2018'""")  # noqa

    note = models.CharField(max_length=512, blank=True, default='')

    objects = querysets.MembershipQuerySet.as_manager()

    class Meta:
        unique_together = ('member', 'member_type', 'valid_from')

    def __str__(self):
        string = "[{member_type}] #{num} {name}".format(
            member_type=self.member_type,
            num=self.member.number,
            name=self.member.name)
        if self.is_current:
            if self.valid_until:
                return "{string} (current) Expires: {date}".format(
                    string=string,
                    date=self.valid_until)
            else:
                return "{string} [{special}] (current)".format(
                    string=string,
                    special=self.special)
        else:
            return "{string} (renewable) Expired: {date}".format(
                string=string,
                date=self.valid_until)

    def clean(self):
        if self.member_type == 'special' and not self.special:
            raise ValidationError(
                "Must add 'special' explanation for special memberships.")

    def is_current(self):
        if not self.valid_until:
            return True
        if self.valid_until >= timezone.now().date():
            return True
        else:
            return False


class MembershipTag(models.Model):

    membership = models.ForeignKey('members.Membership')

    # `Given by` makes sense for this class as exchange of a physical object
    # will always have a human-to-human component. Not necessarily true with
    # other classes in this app.
    given_by = models.ForeignKey('auth.User')

    given_by_name = models.CharField(max_length=128, blank=True, default='')

    given_at = models.DateTimeField(auto_now_add=True, editable=True)

    given_tag = models.BooleanField(default=False)

    given_card = models.BooleanField(default=False)


@python_2_unicode_compatible
class Payment(models.Model):

    member = models.ForeignKey(Member)

    payment_method = models.CharField(max_length=128,
                                      choices=settings.PAYMENT_METHODS,
                                      default=settings.PAYMENT_METHODS[0][0])

    payment_ref = models.CharField(max_length=1024, blank=True, default='')

    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)

    created_at = models.DateTimeField(auto_now_add=True, editable=True)

    class Meta(object):
        ordering = ['member__name', 'created_at']

    def __str__(self):
        return "#{num} ${amount_paid} [{payment_method}] ({name})".format(
            payment_method=self.payment_method,
            amount_paid=self.amount_paid,
            num=self.member.number,
            name=self.member.name
        )


class TemporaryMember(models.Model):
    """ Anybody can complete the form, it doesn't mean it's right and must be
    approved.
    """

    created_at = models.DateTimeField(auto_now_add=True)

    # APPROVAL manually added
    is_checked = models.BooleanField(default=False)

    is_approved_paid = models.BooleanField(default=False)

    approved_payment_method = models.CharField(
        max_length=255, blank=True, default='',
        choices=settings.PAYMENT_METHODS,
    )

    approved_by = models.ForeignKey('auth.User', blank=True, null=True)

    approved_at = models.DateTimeField(blank=True, null=True)

    # Payment type set by user, checked by staff
    payment_method = models.CharField(
        blank=True, default='',
        max_length=255, choices=settings.PAYMENT_METHODS,)

    payment_source = models.CharField(
        blank=True, default='',
        max_length=255, choices=settings.PAYMENT_METHODS,)

    # MEMBER
    # Member created automatically after manual staff approval
    member = models.ForeignKey('members.Member', blank=True, null=True)

project/members/forms.py
# -*- coding: utf-8 -*-
from django import forms

from phonenumber_field.modelfields import PhoneNumberField
from project.rolodex.models import Email, Phone

from . import settings
from .models import TemporaryMember


class TemporaryMemberForm(forms.Form):

    member_type = forms.ChoiceField(
        widget=forms.RadioSelect(),
        choices=settings.MEMBERS_TYPES,
        initial=settings.MEMBERS_TYPES[0])
    sort_name = forms.CharField(label="Surname")
    ref_name = forms.CharField(label="First name")
    email = forms.EmailField()
    phone = PhoneNumberField()
    address = forms.CharField(widget=forms.Textarea)
    suburb = forms.CharField()
    postcode = forms.CharField()
    state = forms.CharField(initial="ACT")
    country = forms.CharField(initial="Australia")
    dob = forms.DateField(
        input_formats=('%d/%m/%Y', '%d-%m-%Y'),
        label="Birthday",
        help_text="Optional and confidential, so we can wish you happy birthday.",  # noqa
        required=False)
    year = forms.IntegerField(
        widget=forms.Select(choices=settings.YEAR_CHOICES),
        label="My generation:",  # noqa
        help_text="Did you know that there are more Generation Yers than Baby Boomers? Please answer this for our curiosity, so we can try to look after you the best.",  # noqa
        min_value=1890, max_value=2017)
    payment_method = forms.ChoiceField(
        widget=forms.RadioSelect(),
        choices=[('', '---')] + settings.PAYMENT_METHODS)
    survey_games = forms.CharField(
        required=False,
        widget=forms.Textarea,
        label="What's your favourite game?",
        help_text="List as many as you like.")
    survey_food = forms.CharField(
        required=False,
        widget=forms.Textarea,
        label="What food, drink or pizza would you like see on our menu?",  # noqa
        help_text="Say as much as you want.")
    survey_hear = forms.CharField(
        required=False,
        widget=forms.Textarea,
        label="How did you hear about us?",
        help_text="Tell us a story.")
    survey_suggestions = forms.CharField(
        required=False,
        widget=forms.Textarea,
        label="Any suggestions you would have for us?",
        help_text="We're still pretty new and learning as we go!")
    special = forms.CharField(
        label="other/special membership add reason",
        help_text="Add the reason for your special membership. Special memberships are arranged for you by Guild staff or management. Ignore otherwise.",  # noqa
        required=False)

    def __init__(self, *args, **kwargs):
        super(TemporaryMemberForm, self).__init__(*args, **kwargs)
        self.request = kwargs.pop('request', None)

        self.fields['dob'].widget.attrs['placeholder'] = 'dd/mm/yyyy'
        self.fields['special'].widget.attrs['placeholder'] = '"other" membership explanation'  # noqa


class BlankForm(forms.Form):

    input_class = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=[('member', 'Member'), ('membership', 'Membership')])

    input_data = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 15, 'cols': 100}))

templates/members/base.html
{% extends "base.html" %}

templates/members/default_form.html
{% extends "members/base.html" %}


{% block title %}{{ homepage.title }} - {{ block.super }}{% endblock %}


{% block content %}
<div class="row">

  <h1>Import Members</h1>

  <p>{{ success_obj|length }} successfully created/found.</p><br>

  <form method="post" action="/members/import/" id="id-form">{% csrf_token %}


    <style>
      #id_input_data {height: 250px;}
    </style>
    {% for field in form %}
    {{ field }}<br>
    {% endfor %}
<input type="submit" value="OK">

  </form>

  {% if class == membership %}
    {% for obj in success_obj %}
    {{ obj }}<br>
    {% endfor %}
  {% else %}
  {% for obj in success_obj %}
    {{ obj }}{% if obj.memberships_set.all %} -- {{ obj.memberships_set.all }}{% endif %}<br>
  {% endfor %}
  {% endif %}

</div>
{% endblock %}

templates/members/member_approval.html
{% extends 'members/base.html' %}


{% block content %}


<h1>Approve New Members</h1>

{% if new_member %}

<div class="alert alert-success" >
  <strong>Approved:</strong> New Member Number: #{{ new_member.number }}
  <p><a href="{{ new_member.get_absolute_url }}">{{ new_member }}</a></p>

</div>

{% endif %}

<div class="row">
<span class="alert alert-danger pull-left text-left">
  Must be approved one at a time.<br>
  Please <b>check details</b> before approving.<br>
  User <i>'Defer'</i>
  option if potentially not genuine or duplicate.
</span>
</div>

{% for obj in obj_list_new %}
<div class="row" style="{% cycle 'background-color: #333' ''  %}">
<form action="" method="post">
  {% csrf_token %}

  <div class="col-md-3">
    <b>{{ obj.name }}</b><br>
    {{ obj.email }}<br>
    {{ obj.phone }}<br>

    <small style="font-family: monospace; font-size: 0.7em; color: #777;">{{ obj.created_at }}</small>
    <a target="_blank" href="{% url "admin:members_temporarymember_change" obj.pk %}" style="white-space:nowrap">
      <small>(edit)</small>
    </a>
  </div>
  <div style="whitespace: nowrap">

    <select name="member_type">
      {% for option in member_types %}
      <option {% if obj.member_type == option.0 %}selected{% endif %}>{{ option.1 }}</option>
      {% endfor %}
    </select>

    <select name="payment_method">
      {% for option in payment_methods %}
      <option {% if obj.payment_method == option.0 %}selected{% endif %}>{{ option.1 }}</option>
      {% endfor %}
    </select>
    $<input type="number" name="amount_paid" step="0.50" value="15.00" style="width: 6em">
    <input type="text" name="payment_ref" placeholder="reference" style="width: 5em">
    <input type="hidden" name="pk" value="{{ obj.pk }}">  &nbsp;
  </div>

  <div style="whitespace: nowrap">
    Approve: &nbsp;  <input type="checkbox" name="approve"> &nbsp;
    Given tag?: &nbsp;  <input type="checkbox" name="has_tag"> &nbsp;
    <button type="submit" class="hidden-print btn btn-default btn-lg">
      <i class="fa fa-check fa-fw"></i>
      <span class="network-name">Submit</span>
    </button>
     &nbsp; Defer: &nbsp;  <input type="checkbox" name="defer">
  </div>
</form>
</div>
{% endfor %}


{% if obj_list_old %}
<h3 style="opacity: 0.4;">Deferred</h3>
<p style="opacity: 0.4;">Likely not genuine or duplicate.</p>
{% endif %}

{% for obj in obj_list_old %}
<div class="row" style="opacity: 0.4; {% cycle 'background-color: #333' ''  %}">
<form action="" method="post">
  {% csrf_token %}

  <div class="col-md-3">
    <b>{{ obj.name }}</b><br>
    {{ obj.email }}<br>
    {{ obj.phone }}<br>

    <small style="font-family: monospace; font-size: 0.7em; color: #777;">{{ obj.created_at }}</small>
    <a target="_blank" href="{% url "admin:members_temporarymember_change" obj.pk %}" style="white-space:nowrap">
      <small>(edit)</small>
    </a>
  </div>

  <div style="whitespace: nowrap">
    <select name="member_type">
      {% for option in member_types %}
      <option {% if obj.member_type == option.0 %}selected{% endif %}>{{ option.1 }}</option>
      {% endfor %}
    </select>
    <select name="payment_method">
      {% for option in payment_methods %}
      <option {% if obj.payment_method == option.0 %}selected{% endif %}>{{ option.1 }}</option>
      {% endfor %}
    </select>
    $<input type="number" name="amount_paid" step="0.50" value="15.00" style="width: 6em">
    <input type="text" name="payment_ref" placeholder="reference" style="width: 5em">
    <input type="hidden" name="pk" value="{{ obj.pk }}">  &nbsp;
  </div>

  <div style="whitespace: nowrap">
    Approve: &nbsp;  <input type="checkbox" name="approve"> &nbsp;
    Given tag?: &nbsp;  <input type="checkbox" name="has_tag"> &nbsp;
    <button type="submit" class="hidden-print btn btn-default btn-lg">
      <i class="fa fa-check fa-fw"></i>
      <span class="network-name">Submit</span>
    </button>
  </div>

</form>
</div>
{% endfor %}

{% endblock %}

templates/members/member_detail.html
{% extends 'members/base.html' %}


{% block content %}

<h1>Member #{{ obj.number }}</h1>

<div class="row">
<div class="box">

  <p>
    <b>{{ obj.name }}</b>
    <br>{% for email in obj.emails.all %}{{ email }}{% endfor %}
    <br>{% for phone in obj.phones.all %}{{ phone }}{% endfor %}
  </p>
  <br>

{% for membership in obj.membership_set.all %}

{% if membership.member_type == "special" %}
  <p>Special Member: <b>{{ membership.special }}</b><br>
{% else%}
  <p>Member type: <b>{{ membership.get_member_type_display }}</b><br>
{% endif %}
  Member since: <b>{{ membership.valid_from }}</b></p>

  {% if membership.is_current %}
<span class="alert alert-success pull-left text-left">
  {% if membership.valid_until %}
  Active until:
  <b>{{ membership.valid_until }}</b>
  {% else %}
  Life Member
  {% endif %}
  <i class="fa fa-check" aria-hidden="true"></i>
</span>
  {% else %}
<span class="alert alert-warning pull-left text-left">
  Was active up to: <b>{{ membership.valid_until }}</b>
  <i class="fa fa-calendar" aria-hidden="true"></i><br>
  <a href="{% url 'members:member_detail' obj.pk %}">
    Renew now <i class="fa fa-heart" aria-hidden="true"></i>
  </a>
</span>
  {% endif %}
</div>
</div>

{% endfor %}


{% endblock %}

templates/members/member_form.html
{% extends 'members/base.html' %}


{% block content %}

<h1>Member Sign Up</h1>

<form action="" method="post">
  {% csrf_token %}

  <table id="member-form">
    {{ form.as_table }}

    <tr class="hidden-print submit-buttons">
      <th></th>
      <td>
        <button type="submit" class="hidden-print btn btn-default btn-lg">
          <i class="fa fa-save fa-fw"></i>
          <span class="network-name">Save</span>
        </button>
        <button type="submit" class="hidden-print btn btn-default btn-lg" id="remove">
          <i class="fa fa-trash fa-fw"></i>
          <span class="network-name">Cancel</span>
        </button>
      </td>
    </tr>
  </table>

</form>

{% endblock %}

templates/members/member_list.html
{% extends 'members/base.html' %}



{% block content %}

<h1>Member #{{obj.number}}</h1>

    <div class="table-responsive">
      <table class="table table-hover" width="100%" id="dataTable" cellspacing="0">

        <thead>
          <tr>
            <th>#</th>
            <th>Surname</th>
            <th>First Name</th>
            <th>Type</th>
            <th style="text-align: center;" >Valid Until</th>
            <th>&nbsp;</th>
          </tr>
        </thead>

        {% for obj in object_list %}
        <tr id="row{{ obj.pk }}" data-pk="" >
          <td class="value">
            <div class="nowrap"><b>
                <a href="{% url 'members:member_detail' obj.member.number %}">
                  #{{ obj.member.number|stringformat:"04d" }}
                </a>
            </b></div>
          </td>
          <td style="text-align: left;" class="value">
            <div class="nowrap">
              <a href="{% url 'members:member_detail' obj.member.number %}">
                {{ obj.member.sort_name }}
              </a>
            </div>
          </td>
          <td style="text-align: left;" class="value">
            <div class="nowrap">
              <a href="{% url 'members:member_detail' obj.member.number %}">
                {{ obj.member.ref_name }}
              </a>
            </div>
          </td>
          <td class="description">
            {{ obj.get_member_type_display }}
            {% if obj.member_type == 'special' %}:  {{ obj.special }}{% endif %} <br>
          </td>
          <td style="text-align: center;" class="valid_until">
            {% if obj.valid_until %}
              {% if obj.is_current %}
              <p class="list-group-item-success">
              {% else  %}
              <p class="list-group-item-danger">
              {% endif %}
              {{ obj.valid_until }}
              </p>
            {% else %}
              <p class="list-group-item-info"><i> ** lifetime  **</i></p>
            {% endif %}
          </td>
          <td>
            &nbsp:
          </td>
        </tr>
        {% endfor %}

      </table>
    </div>
{% endblock %}


{% block extra_static %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jqc-1.12.4/dt-1.10.15/r-2.1.1/sc-1.4.2/datatables.min.js"></script>
    <script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
    $('#dataTable').DataTable({
             "order": [[0, "desc"]],
             "lengthMenu": [
                [50, 100, 250, -1],
                [50, 100, 250, "All"]],
              "columnDefs": [
                  { "targets": 0, "type": "html" }
              ],
        });
    });
    </script>
    <style>
      #dataTable_filter > label > input {width: 35em; margin-left: 14px;}
    </style>
{% endblock %}

templates/members/temporarymember_success.html
{% extends 'members/base.html' %}


{% block content %}


<h1>Thank you!</h1>

Your membership application has been submitted.

You can pay online here:<br>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="EH6FCUWKGHCSY">
<table>
<tr><td><input type="hidden" name="on0" value="Membership Type">Membership Type</td></tr><tr><td><select name="os0">
	<option value="Standard">Standard $15.00 AUD</option>
	<option value="Student">Student $11.50 AUD</option>
	<option value="Family">Family $40.00 AUD</option>
</select> </td></tr>
</table>
<input type="hidden" name="currency_code" value="AUD">
<input type="image" src="https://www.paypalobjects.com/en_AU/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_AU/i/scr/pixel.gif" width="1" height="1">
</form>



You will be notified when your membership is approved.


<br><br>
<p>
<a href="{% url 'members:member_form' %}"
<button type="submit" class="hidden-print btn btn-default btn-lg">
          <i class="fa fa-plus-circle fa-fw"></i>
          <span class="network-name">New Form</span>
</button>
</a>
</p>

{% endblock %}