project/blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.EntryListView.as_view(), name='entry_list'),

    url(r'^(?P<page>\d+)$', views.EntryListView.as_view(), name='entry_list'),

    url(r'^latest\.xml$', feeds.EntryFeed(), name='entry_feed'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<slug>[\w-]+)$',
        views.EntryDetailView.as_view(), name='entry_detail'),

]

urlpatterns = [url(r'^', include(urls, namespace='blog'))]

project/menus/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.MenuTypeListView.as_view(), name='menutype_list'),

    url(r'^(?P<page>\d+)$', views.MenuTypeListView.as_view(), name='menutype_list'),

    url(r'^latest\.xml$', feeds.MenuFeed(), name='menu_feed'),
]

urlpatterns = [url(r'^', include(urls, namespace='menus'))]

project/site/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.HomepageDetailView.as_view(), name='homepage_detail'),

]


urlpatterns = [url(r'^', include(urls, namespace='site'))]

project/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from debug_toolbar import urls as debug_toolbar_urls
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from project.sitemaps import sitemaps


urlpatterns = [

    # Site
    url(r'^', include('project.site.urls')),

    # Blog
    url(r'^blog/', include('project.blog.urls')),

    # Menu
    url(r'^menus/', include('project.menus.urls')),

    # Games Library
    url(r'^games/', include('project.library.urls')),

    # Bookings
    url(r'^bookings/', include('project.bookings.urls')),

    # Members
    url(r'^members/', include('project.members.urls')),

    # Robots
    url(r'^robots\.txt', include('robots.urls')),

    # XML Sitemap
    url(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # Admin Docs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # TinyMCE
    url(r'^tinymce/', include('tinymce.urls')),

]


if settings.DEBUG:
    # Only serve media files if in a development environment
    from django.conf.urls.static import static
    from django.views.generic import TemplateView

    urlpatterns += [
        url(r'^errors/404$', TemplateView.as_view(template_name='404.html')),
        url(r'^errors/500$', TemplateView.as_view(template_name='500.html')),
        url(r'^__debug__/', include(debug_toolbar_urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import querysets, settings
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from project import utils
from taggit.managers import TaggableManager


def get_current_site():
    try:
        return Site.objects.get_current().pk
    except Site.DoesNotExist:
        pass


@python_2_unicode_compatible
class Entry(models.Model):

    title = models.CharField(max_length=200, blank=True, default='')

    heading = models.CharField(max_length=200, blank=True, default='')

    summary = models.TextField(blank=True, default='')

    featured_image = models.ImageField(max_length=1024,
                                       upload_to='entry_featured',
                                       help_text='Ensure bigger than 790x377 if going to be featured in carousel.',
                                       blank=True, default='')

    featured_order = models.IntegerField(default=0)

    featured_content = models.TextField(blank=True, default='')

    content = models.TextField(blank=True, default='')

    summary = models.TextField(default='', blank=True)

    tags = TaggableManager(blank=True)

    meta_description = models.CharField(max_length=200, blank=True, default='')

    is_enabled = models.BooleanField('enabled', db_index=True, default=True)

    is_featured = models.BooleanField('featured', db_index=True, default=False)

    site = models.ForeignKey('sites.Site', default=get_current_site,
                             related_name='blog_entries',
                             on_delete=models.PROTECT)

    slug = models.SlugField(unique_for_date='publish_at')

    publish_at = models.DateTimeField(db_index=True, default=timezone.now)

    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    updated_at = models.DateTimeField(auto_now=True, editable=False)

    objects = querysets.QuerySet.as_manager()

    class Meta(object):
        ordering = ['featured_order', '-publish_at', 'title']
        unique_together = ['site', 'publish_at', 'slug']
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        server_timezone = timezone.pytz.timezone(settings.TIME_ZONE)

        if timezone.is_naive(self.publish_at):
            publish_at = server_timezone.localize(self.publish_at)
        else:
            publish_at = server_timezone.normalize(self.publish_at)

        return reverse('blog:entry_detail',
                       kwargs={'year': '%04d' % (publish_at.year),
                               'month': '%02d' % (publish_at.month),
                               'slug': self.slug})

    def get_next(self):
        queryset = self.__class__.objects.exclude(pk=self.pk).filter(
            site=self.site, publish_at__gte=self.publish_at
            ).active().order_by('publish_at')
        return queryset.first()

    def get_previous(self):
        queryset = self.__class__.objects.exclude(pk=self.pk).filter(
            site=self.site, publish_at__lte=self.publish_at
            ).active().order_by('-publish_at')
        return queryset.first()

    def is_active(self):
        return self in self.__class__.objects.filter(pk=self.pk).active()
    is_active.boolean = True
    is_active.short_description = 'active'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = utils.generate_unique_slug(
                self.title,
                self.__class__.objects.filter(
                    site=self.site,
                    publish_at__year=self.publish_at.year,
                    publish_at__month=self.publish_at.month,
                    publish_at__day=self.publish_at.day))
        return super(Entry, self).save(*args, **kwargs)

project/blog/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from .models import Entry
from django import forms
from tinymce.widgets import TinyMCE


class EntryAdminForm(forms.ModelForm):

    class Meta(object):
        fields = ['title', 'heading', 'summary', 'featured_content', 'content',
                  'meta_description', 'is_enabled', 'is_featured', 'site',
                  'slug', 'publish_at', 'tags']
        model = Entry
        widgets = {'content': TinyMCE()}

project/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import settings
from .models import Entry
from django.shortcuts import redirect
from django.views import generic


class EntryDetailView(generic.DetailView):

    allow_future = True

    date_field = 'publish_at'

    model = Entry

    month_format = '%m'

    def get_queryset(self, *args, **kwargs):
        queryset = super(EntryDetailView, self).get_queryset(*args, **kwargs)
        return queryset.current_site().active()


class EntryListView(generic.ListView):

    model = Entry

    paginate_by = settings.ENTRIES_PAGINATE_BY

    def get(self, *args, **kwargs):
        page = self.kwargs.get('page', None)
        if page is not None and int(page) < 2:
            return redirect('blog:entry_list', permanent=True)
        return super(EntryListView, self).get(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        queryset = super(EntryListView, self).get_queryset(*args, **kwargs)
        return queryset.current_site().active()

templates/blog/base.html
{% extends "base.html" %}

templates/blog/entry_detail.html
{% extends "blog/base.html" %}


{% block title %}{{ entry.title }} - {{ block.super }}{% endblock %}


{% block meta %}
  {{ block.super }}
  {% if entry.meta_description %}<meta name="description" content="{{ entry.meta_description }}" />{% endif %}
{% endblock %}


{% block content %}

  <h1>{{ entry.heading|default:entry.title }}</h1>

  {% if entry.featured_content %}<div>{{ entry.featured_content }}</div>{% endif %}
  {% if entry.content %}<div>{{ entry.content|safe }}</div>{% endif %}

<img class="img-responsive img-full" src="{{MEDIA_URL}}{{ entry.featured_image }}" alt="">

{% endblock %}

templates/blog/entry_list.html
{% extends "blog/base.html" %}
{% load thumbnail %}


{% block title %}Blog entries - {{ block.super }}{% endblock %}


{% block extrahead %}

  {{ block.super }}

  <link rel="alternate" href="{% url "blog:entry_feed" %}" type="application/atom+xml" title="Latest blog entries" />

  {% if page_obj.paginator.num_pages > 1 %}{% spaceless %}
    {% if page_obj.has_previous %}<link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "blog:entry_list" %}{% else %}{% url "blog:entry_list" page=page_obj.previous_page_number %}{% endif %}" />{% endif %}
    {% if page_obj.has_next %}<link rel="next" href="{% url "blog:entry_list" page=page_obj.next_page_number %}" />{% endif %}
  {% endspaceless %}{% endif %}

{% endblock %}


{% block content %}

  <h1>Blog entries</h1>

  {% for entry in entry_list %}
    {% if forloop.first %}<ul>{% endif %}
      <li>
        <a class="carousel-img" href="{{ entry.get_absolute_url }}">
          {% thumbnail entry.featured_image "100x100" crop="center" as im %}
          <img src="{{ im.url }}" width="100" height="100">
          {% endthumbnail %}
        </a>
        <a href="{{ entry.get_absolute_url }}">{{ entry.publish_at|date:"SHORT_DATE_FORMAT" }} {{ entry }}</a>
        <p>{{ entry.summary }}</p>
      </li>
    {% if forloop.last %}</ul>{% endif %}
  {% endfor %}

  {% if page_obj.paginator.num_pages > 1 %}
  <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</p>
  <ul>
    {% if page_obj.has_previous %}<a href="{% if page_obj.previous_page_number == 1 %}{% url "blog:entry_list" %}{% else %}{% url "blog:entry_list" page=page_obj.previous_page_number %}{% endif %}" rel="previous">Previous</a>{% endif %}
    {% if page_obj.has_next %}<li><a href="{% url "blog:entry_list" page_obj.next_page_number %}" rel="next">Next</a></li>{% endif %}
  </ul>
  {% endif %}

{% endblock %}