project/blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.EntryListView.as_view(), name='entry_list'),

    url(r'^(?P<page>\d+)$', views.EntryListView.as_view(), name='entry_list'),

    url(r'^latest\.xml$', feeds.EntryFeed(), name='entry_feed'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<slug>[\w-]+)$',
        views.EntryDetailView.as_view(), name='entry_detail'),

]

urlpatterns = [url(r'^', include(urls, namespace='blog'))]

project/bookings/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import views
from django.conf.urls import include, url
from django.contrib.auth.decorators import permission_required

BOOKINGS_PERMISSION_REQUIRED = 'bookings.change_booking'


urls = [

    url(r'^show/numbers/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingListNumView.as_view()
        ),
        name='booking_list_num'),

    url(r'^show/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingListView.as_view()
        ),
        name='booking_list'),

    url(r'^form/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.FormView.as_view(),
        ),
        name='booking_default_form'),

    url(r'^post/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            # views.PostView.as_view(),
            views.post_view
        ),
        name='booking_default_post'),

    url(r'^show/(?P<page>\d+)$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingListView.as_view()
        ),
        name='booking_list_pagination'),

    url(r'^cancelled/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingCancelledView.as_view()
        ),
        name="booking_list_cancelled"),

    url(r'^future/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingFutureView.as_view()
        ),
        name='booking_future'),

    url(r'^today/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingTodayArchiveView.as_view()
        ),
        name="booking_today"),

    url(r'^(?P<year>\d{4})/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingYearArchiveView.as_view()
        ),
        name="booking_year"),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingMonthArchiveView.as_view()
        ),
        name="booking_month"),

    url(r'^(?P<year>\d{4})/week/(?P<week>\d+)/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingWeekArchiveView.as_view()
        ),
        name="booking_week"),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingDayArchiveView.as_view()
        ),
        name="booking_day"),

    url(r'^reservation_sheet/$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.ReservationSheetPDFView.as_view()
        ),
        name="reservation_sheet"),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<slug>[\w-]+)$',
        permission_required(BOOKINGS_PERMISSION_REQUIRED)(
            views.BookingDetailView.as_view()
        ),
        name='booking_detail'),

    url(r'^$',
        views.BookingCreateView.as_view(),
        name="booking_add"),

    url(r'^time/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        views.BookingTimeView.as_view(),
        name='booking_times'),

    # Used to save some horrible frontend code to reformat date on
    # bookings form.
    url(r'^time/(?P<day>\d{2})/(?P<month>\d{2})/(?P<year>\d{4})/$',
        views.BookingTimeView.as_view(),
        name='booking_times_reversed'),

    url(r'^(?P<code>[\w-]+)/run/$',
        views.BookingRunView.as_view(),
        name="booking_run"),

    url(r'^(?P<code>[\w-]+)/success/$',
        views.BookingSuccessView.as_view(),
        name="booking_success"),

    url(r'^(?P<code>[\w-]+)/$',
        views.BookingUpdateView.as_view(),
        name="booking_update"),

]

urlpatterns = [url(r'^', include(urls, namespace='bookings'))]

project/members/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.conf.urls import include, url
from django.contrib.auth.decorators import permission_required

from . import views

MEMBERS_PERMISSION_REQUIRED = 'members.can_change_member'


urls = [

    url(r'^new/',
        views.member_create_view,
        name='member_form'),

    url(r'^success/',
        views.TemporaryMemberSuccessView.as_view(),
        name='temporarymember_success_view'),

    url(r'^approve/',
        permission_required(MEMBERS_PERMISSION_REQUIRED)(
            views.member_approval_view,
        ),
        name='member_approval'),

    url(r'^import/$',
        permission_required(MEMBERS_PERMISSION_REQUIRED)(
            views.import_view
        ),
        name='members_import'),

    url(r'^list/$',
        permission_required(MEMBERS_PERMISSION_REQUIRED)(
            views.MemberListView.as_view(),
        ),
        name='member_list'),

    url(r'^\+/(?P<number>\d+)$',
        views.member_detail_view,
        name='member_detail'),

]

urlpatterns = [url(r'^', include(urls, namespace='members'))]

project/menus/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.MenuTypeListView.as_view(), name='menutype_list'),

    url(r'^(?P<page>\d+)$', views.MenuTypeListView.as_view(), name='menutype_list'),

    url(r'^latest\.xml$', feeds.MenuFeed(), name='menu_feed'),
]

urlpatterns = [url(r'^', include(urls, namespace='menus'))]

project/site/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.HomepageDetailView.as_view(), name='homepage_detail'),

]


urlpatterns = [url(r'^', include(urls, namespace='site'))]

project/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from debug_toolbar import urls as debug_toolbar_urls
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from project.sitemaps import sitemaps


urlpatterns = [

    # Site
    url(r'^', include('project.site.urls')),

    # Blog
    url(r'^blog/', include('project.blog.urls')),

    # Menu
    url(r'^menus/', include('project.menus.urls')),

    # Games Library
    url(r'^games/', include('project.library.urls')),

    # Bookings
    url(r'^bookings/', include('project.bookings.urls')),

    # Members
    url(r'^members/', include('project.members.urls')),

    # Robots
    url(r'^robots\.txt', include('robots.urls')),

    # XML Sitemap
    url(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # Admin Docs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # TinyMCE
    url(r'^tinymce/', include('tinymce.urls')),

]


if settings.DEBUG:
    # Only serve media files if in a development environment
    from django.conf.urls.static import static
    from django.views.generic import TemplateView

    urlpatterns += [
        url(r'^errors/404$', TemplateView.as_view(template_name='404.html')),
        url(r'^errors/500$', TemplateView.as_view(template_name='500.html')),
        url(r'^__debug__/', include(debug_toolbar_urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/events/models.py
import datetime
from . import querysets
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.encoding import python_2_unicode_compatible
from photologue.models import Photo, Gallery
from taggit.managers import TaggableManager

from project.utils import get_current_site

def photo_default_main(self=None):
    if self:
        return self.main_image

def photo_default_poster(self=None):
    if self:
        return self.poster


@python_2_unicode_compatible
class Event(models.Model):
    is_enabled  = models.BooleanField(default=True)

    spotlight   = models.BooleanField(default=False)
    spotlight_order = models.IntegerField(default=0)
    recurring   = models.BooleanField(default=False)
    recur_description  = models.CharField(max_length=255, verbose_name="Date Description",
                                          help_text="eg, 'Every Thursday'", blank=True, default='')
    event_image = models.ForeignKey(
        Photo,
        blank=True, null=True,
        related_name="event_image",
    )
    main_image  = models.ForeignKey(
        Photo,
        blank=True, null=True,
        related_name="main_image",
    )
    poster      = models.ForeignKey(
        Photo,
        blank=True, null=True,
        related_name="poster",
    )

    event_name  = models.CharField(max_length=255)
    slug        = models.SlugField(max_length=255, blank=True, default='')
    date        = models.DateField(blank=True, null=True, help_text="Events without dates aren't displayed, except if recurring.")
    time        = models.TimeField(blank=True, null=True,
                                   help_text="24 HOUR TIME. Add a usual time for recurring events. This will be over-ridden if specific time added.")

    expires = models.DateField(blank=True, null=True, help_text="Optional.")

    paypal = models.CharField(max_length=65, blank=True, default='',
                              help_text="Paypal provided hosted_button_id")
    door_cost   = models.CharField(max_length=255, blank=True, default='', verbose_name='cost')
    ticket_url  = models.URLField(blank=True, default='',
        help_text="External ticket URL (if applicable)")
    gig_details = models.TextField(max_length=999, verbose_name="Snippet Text",
        help_text="Short text. LIMITED TO 175 words.")
    content = models.TextField(blank=True, default='',
        help_text="More artist info / bio.")
    extra_URLs  = models.TextField(blank=True, default='',
        help_text="eg. artist Myspace / website, separate multiple urls  with commas.")
    post_event_gallery = models.ForeignKey(Gallery, blank=True, null=True)

    extra_images = models.ManyToManyField(
        Photo, blank=True,
    )

    twitter_account = models.CharField(max_length=100, blank=True, default='')
    facebook_event = models.CharField(max_length=255, blank=True, default='')

    tags = TaggableManager(blank=True)

    objects = querysets.QuerySet.as_manager()

    def save(self):
        self.slug = slugify(self.event_name)
        if self.spotlight and not self.spotlight_order:
            self.spotlight_order = '999'

        ## set event_image (hidden field with absolute version)
        if not self.event_image:
            if self.main_image:
                self.event_image = self.main_image
            elif self.poster:
                self.event_image = self.poster
            else:
                pass

        super(Event, self).save()
        ## handle date object: ~ add if not || ~ correct image
        e = EventDate.objects.filter(event=self) #, date=self.date)
        if e:
            today = datetime.datetime.today()
            d = e.filter(date__gte=today)
            if d:
                c = d.order_by('date')[0]
                self.date = c.date
                if c.date_image:
                    self.event_image = c.date_image
        else:
            e = EventDate(event=self, date=self.date)
            e.save()
        super(Event, self).save()

    def __str__(self):
        return self.event_name


    class Meta:
        ordering = ['-date', '-recurring']


class EventDate(models.Model):
    event = models.ForeignKey(Event)
    date  = models.DateField()
    time  = models.TimeField(blank=True, null=True)
    additional = models.CharField(max_length=999, blank=True,
                                  default='', help_text="Make it special.")
    date_image  = models.ForeignKey(
        Photo,
        blank=True, null=True,
        related_name="date_image",
        )

    def __unicode__(self):
        return '%s -- %s' % (self.date, self.event.event_name)


    class Meta:
        ordering = ['-date']


class EventGallery(models.Model):
    event = models.ForeignKey(Event)
    photo = models.ForeignKey(Photo)
    order = models.IntegerField(default=0)

    def __unicode__(self):
        return self.event.event_name


class EventVideo(models.Model):
    event = models.ForeignKey(Event)
    video = models.CharField(max_length=255,
                             verbose_name="Youtube video",
                             help_text="YouTube video link.")
    order = models.IntegerField(default=0)

    ## s.find('v=').split('&')[0]
    ## http://www.youtube.com/watch?v=3I6jWE5UIYg&feature=related

    def save(self):
        if not self.order:
            self.order = '999'
        v = self.video
        if v[:4] == 'http':
            self.video = v[v.find('v=')+2:].split('&')[0]
            #"http://www.youtube.com/v/%s&hl=en&fs=1" % v
        super(EventVideo, self).save()

    def __unicode__(self):
        return '%s -- %s' % (self.event.event_name, self.video)

    class Meta:
        ordering = ['order']


class EventUser(models.Model):
    event = models.ForeignKey(Event)
    user = models.ForeignKey(User, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=255, blank=True, default='')
    number_tickets = models.IntegerField(null=True)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    def save(self):
        if not self.order:
            self.order = '999'
        super(ComingEvent, self).save()

    class Meta:
        ordering = ['event']

project/navigation/models.py
from django.db import models


class Menu(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name
    

class MenuItem(models.Model):
    menu = models.ForeignKey(Menu)
    name = models.CharField(max_length=255)
    link = models.CharField(max_length=999)
    order = models.IntegerField()

    def __unicode__(self):
        return self.name
    

project/navigation/views.py
# Create your views here.

templates/_navigation.html
{% load static from staticfiles %}
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="{% url "site:homepage_detail" %}">
        <img src="{% static "sheild-.png" %}" height=24>
      </a>
    </div>

    <div class="navbar-collapse navbar-center navbar-main-collapse collapse" aria-expanded="false" style="height: 1px;">

      <ul class="nav navbar-nav">
        <li class="active">
          <a class="home-link" href="{% url "site:homepage_detail" %}">
            <img src="{% static "sheild-.png" %}" height=24>
          </a>
        </li>

        {% load sitetree %}
        {% sitetree_menu from "MainNavigation" include "trunk"  template "sitetree/custom_menu_bootstrap3.html" %}

        <li>
          <a href="#location" class="page-scroll">
            Find Us <i class="fa fa-map-marker"></i>
          </a>
        </li>
        <li>
          <a href="https://facebook.com/guildhouse.canberra" target="_blank"><i class="fa fa-facebook-square fa-fw"></i></a>
        </li>
      </ul>

  {% if user.is_authenticated %}
  <div class="hidden-print featured_text" style="text-align: center;">
    Logged in: <a href="/admin/">{{ user }}</a> |
    <a href="/admin/">Admin</a> |
    <a href="{% url 'bookings:booking_list' %}">Bookings</a> |
    <a href="{% url 'members:member_approval' %}">Members</a> |
    <a href="/admin/logout/">Log out</a>
  </div>
  {% endif %}


    </div>

    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

templates/base.html
<!DOCTYPE html>{% load static from staticfiles %}
<html lang="en">

<head>
    <title>{% block title %}{{ request.site.name }}{% endblock %} - Board Games Pizza Craft Drinks Canberra</title>
    {% block meta %}
    <meta charset="utf-8">

    {# dev testing only #}
    <meta name="robots" content="noindex" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="google-site-verification" content="ypeEk5RozV8DIeR1EXzRJJdHCNLlfSbM5PpfM2f2tXY" />
    {% endblock %}

    <link rel="icon" type="image/png" href="{% static "favicon.png" %}">
    <link href="{% static "vendor/normalize.css" %}" type="text/css" rel="stylesheet" />
    <link href="{% static "vendor/bootstrap/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "vendor/jquery/jquery-ui.min.css" %}" type="text/css" rel="stylesheet" />
    <link href="{% static "vendor/jquery/jquery-ui.structure.min.css" %}" type="text/css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css" rel="styleseets" />
    <link href="{% static "guild.css" %}" type="text/css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


    {% block extrahead %}{% endblock %}
  </head>

<body id="guild-body">

  {% include "_navigation.html" %}

    <!-- Branding -->
    <div class="brand"><a href="{% url "site:homepage_detail" %}"><img src="{% static "img/guild_white.png" %}" alt="Guild, Canberra's Board games beer restaurant cafe"></a></div>
    <div class="address-bar">
      <span class="light">Board Games &middot; Restaurant &middot; Canberra</span><br>
      <a href="mailto:reservations@guild.house">reservations@guild.house</a>
      &middot; <a href="tel:+61262572727">02 6257 2727</a>
    </div>

{% if messages %}
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
                </div>
            </div>
        </div>
    </div>
{% endif %}

    {# <!-- /.container --> #}
    <div class="container">



    {% block sub_nav %}
    {% endblock %}

    {% if not user.is_anonymous %}{% endif %}


    {% block box_above %}
    {% endblock %}

    {% block container %}
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
    {% block content %}
    {% endblock %}
                </div>
            </div>
        </div>
    {% endblock %}

    {% block box_below %}
    {% endblock %}

        <div class="row hidden-print" id="location">
            <div class="box">
                <div class="col-lg-12">
                  <h2>Where? Here!</h2>
                  <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
                          src="https://www.google.com/maps/embed/v1/place?key=AIzaSyB26kOQoCsLOLJT7wpDWvz4-KFwM5sWy0k&q=Guild+Canberra" allowfullscreen>
                  </iframe>
                  <p>We're located in the heart of Canberra City, downstairs at Bailey's Arcade. Next to the Civic bus interchange, across from the Canberra Theatre.</p>
                </div>
            </div>
        </div>

    <footer class="hidden-print">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                <h2>Contact Us</h2>
                </div>
                <div class="col-lg-12 text-center">
                <p>Feel free to email us to make a reservation, provide some feedback, or to just say hello!</p>
                <p><a href="mailto:hello@guild.house">hello@guild.house</a><br>
                  <a href="tel:+61262572727">02 6257 2727</a></p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://facebook.com/guildhouse.canberra" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                    </li>
                </ul>
                </div>
            </div>
        </div>
    </footer>
    </div>
    {# <!-- /.container --> #}
    <script src="{% static "vendor/jquery/jquery.js" %}"></script>
    <script src="{% static "guild.js" %}"></script>
    <script src="{% static "vendor/jquery/jquery-ui.min.js" %}" type="text/javascript"></script>
    <script src="{% static "vendor/jquery/jquery.easing.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/bootstrap.min.js" %}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000
    })
    </script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-70431612-1', 'auto');
      ga('send', 'pageview');
    </script>

    {% block extra_static %}
    {% endblock %}

</body>

</html>

templates/feed_events.html
<table style="color: #fff; display: block; font-family: Arial, Helvetica, sans-serif; background-color: #330000;" >
  <tr>
    <td valign="top" style="padding: 10px 0 10px 10px;">
<img align="left" src="{% if event.main_image %}{{event.main_image.get_feed_thumb_url}}{% else %}{{event.poster.get_feed_thumb_url}}{% endif %}" border="0" >    </td>
    <td valign="top" style="padding: 10px;">
<h1 style="font-size: 22px; line-height: 18px; color: #ccc;">
  {{event.date|date:"l"|upper}} {{event.time|time:"fA"}}<br />
  {{event.date|date:"F j"|upper}} {% if event.date|date:"Y" == year %}{{event.date|date:"Y"}}{% endif %}<br />
  <a href="{% include 'url_event.html' %}" style="color: #fff; text-decoration: none;">{{event.event_name|upper|safe}}</a>
</h1>
<p style="color:#fff; font-size: .8em;">{{event.gig_details|safe}}</p>
<h2 style="font-size: 18px; line-height: 16px; color: #fff;">
	<a href="{% include 'url_event.html' %}" style="text-decoration: none; color: #ccc;">//MORE INFO</a>
    {% if event.door_cost %}<br />+{{event.door_cost|upper|safe}}{% endif %}
    {% if event.ticket_url %}<br /><a target="_blank" href="{{event.ticket_url}}" style="color:#fff;">+BUY TICKETS</a>{% endif %}
</h2>
    </td>
  </tr>
  <tr style="background-color: #250101;">
    <td colspan="2">&nbsp;</td>
  </tr> 
</table>

templates/include_events.html
{% for event in events %}
{% cycle '  </tr>' '' %}
    <td width="300" valign="top">
    <a href="{% include 'url_event.html' %}" style="color:#ccc;">
    <img class="event" src="{% if event.main_image %}{{event.main_image.get_home_week_url}}{% else %}{{event.poster.get_home_week_url}}{% endif %}" align="middle"></a>
	<blockquote>
        <h1>{{event.date|date:"l"|upper}} {{event.time|time:"fA"}}<br />
          {{event.date|date:"F j"|upper}} {% if event.date|date:"Y" == year %}{{event.date|date:"Y"}}{% endif %}<br />
          <span class="white"><a href="{% include 'url_event.html' %}">{{event.event_name|upper|safe}}</a></span>
        </h1>
        {% if event.recurring %}
            {% if recur %}
            {% include 'events/recur_event.html' %}
            {% else %}
                {% for recur in event.eventdate_set.all %}
				{% if event.date == recur.date %}{% include 'events/recur_event.html' %}{% endif %}
                {% endfor %}
	        {% endif %}
        {% endif %}
        <p>{{event.gig_details|safe}}</p>
        <h2><a href="{% include 'url_event.html' %}" style="color:#CCC;">//MORE INFO</a>
            {% if event.door_cost %}<br />+{{event.door_cost|upper|safe}}{% endif %}
            {% if event.ticket_url %}<br /><a target="_blank" href="{{event.ticket_url}}" style="color:#CCC;">+BUY TICKETS</a>{% endif %}
        </h2>
    </blockquote>
    </td>
{% cycle '' '  </tr>' %}
{% endfor %}

templates/include_spotlight.html

<div class="wrapper">
{% if event_detail %}
    <a id="poster" href="/media/{{event.poster.image}}" title="{{event.event_name}} //">
{% else %}
    <a href="{% include 'url_event.html' %}" style="color:#ccc;">
{% endif %}
	    <img class="left" style="clear: both; position: relative; z-index: 1" src="{% if event.poster %}{{event.poster.get_spotlight_main_url}}{% else %}{{event.main_image.get_home_week_url}}{% endif %}">
    </a>
    <div class="right">
        <h1>{% if spotlights %}SPOTLIGHT<br>{% endif %}
            <a style="color: #fff;" href="{% include 'url_event.html' %}">{{event.event_name|upper|safe}}</a><br>
			<a style="color: #ccc;" href="/events/{{event.date|date:'Y/m/d/'}}">
            {{event.date|date:"l"|upper}} {{event.time|time:"fA"}}<br />
            {{event.date|date:"F j"|upper}} {% if event.date|date:"Y" == year %}{{event.date|date:"Y"}}{% endif %}</a><br />
        </h1>
        {% if event.recurring %}
            {% if recur %}
            {% include 'events/recur_event.html' %}
            {% else %}
                {% for recur in event.eventdate_set.all %}
				{% if event.date == recur.date %}{% include 'events/recur_event.html' %}{% endif %}
                {% endfor %}
	        {% endif %}
        {% endif %}
        <p>{{event.gig_details|safe}}</p>
        {% if spotlights or day %}
        <h1><a href="{% include 'url_event.html' %}" style="color:#ccc;">//MORE INFO</a>
    {% if event.door_cost %}<br />+{{event.door_cost|upper|safe}}{% endif %}
    {% if event.ticket_url %}<br /><a target="_blank" href="{{event.ticket_url}}" style="color: #fff;">+BUY TICKETS</a>{% endif %}
        </h1>
        {% endif %}
    </div>
</div>