project/blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.EntryListView.as_view(), name='entry_list'),

    url(r'^(?P<page>\d+)$', views.EntryListView.as_view(), name='entry_list'),

    url(r'^latest\.xml$', feeds.EntryFeed(), name='entry_feed'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<slug>[\w-]+)$',
        views.EntryDetailView.as_view(), name='entry_detail'),

]

urlpatterns = [url(r'^', include(urls, namespace='blog'))]

project/menus/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.MenuTypeListView.as_view(), name='menutype_list'),

    url(r'^(?P<page>\d+)$', views.MenuTypeListView.as_view(), name='menutype_list'),

    url(r'^latest\.xml$', feeds.MenuFeed(), name='menu_feed'),
]

urlpatterns = [url(r'^', include(urls, namespace='menus'))]

project/site/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import views
from django.conf.urls import include, url


urls = [

    url(r'^$', views.HomepageDetailView.as_view(), name='homepage_detail'),

]


urlpatterns = [url(r'^', include(urls, namespace='site'))]

project/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from debug_toolbar import urls as debug_toolbar_urls
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from project.sitemaps import sitemaps


urlpatterns = [

    # Site
    url(r'^', include('project.site.urls')),

    # Blog
    url(r'^blog/', include('project.blog.urls')),

    # Menu
    url(r'^menus/', include('project.menus.urls')),

    # Games Library
    url(r'^games/', include('project.library.urls')),

    # Bookings
    url(r'^bookings/', include('project.bookings.urls')),

    # Members
    url(r'^members/', include('project.members.urls')),

    # Robots
    url(r'^robots\.txt', include('robots.urls')),

    # XML Sitemap
    url(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # Admin Docs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # TinyMCE
    url(r'^tinymce/', include('tinymce.urls')),

]


if settings.DEBUG:
    # Only serve media files if in a development environment
    from django.conf.urls.static import static
    from django.views.generic import TemplateView

    urlpatterns += [
        url(r'^errors/404$', TemplateView.as_view(template_name='404.html')),
        url(r'^errors/500$', TemplateView.as_view(template_name='500.html')),
        url(r'^__debug__/', include(debug_toolbar_urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/events/models.py
import datetime
from . import querysets
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.encoding import python_2_unicode_compatible
from photologue.models import Photo, Gallery
from taggit.managers import TaggableManager

from project.utils import get_current_site

def photo_default_main(self=None):
    if self:
        return self.main_image

def photo_default_poster(self=None):
    if self:
        return self.poster


@python_2_unicode_compatible
class Event(models.Model):
    is_enabled  = models.BooleanField(default=True)

    spotlight   = models.BooleanField(default=False)
    spotlight_order = models.IntegerField(default=0)
    recurring   = models.BooleanField(default=False)
    recur_description  = models.CharField(max_length=255, verbose_name="Date Description",
                                          help_text="eg, 'Every Thursday'", blank=True, default='')
    event_image = models.ForeignKey(
        Photo,
        blank=True, null=True,
        related_name="event_image",
    )
    main_image  = models.ForeignKey(
        Photo,
        blank=True, null=True,
        related_name="main_image",
    )
    poster      = models.ForeignKey(
        Photo,
        blank=True, null=True,
        related_name="poster",
    )

    event_name  = models.CharField(max_length=255)
    slug        = models.SlugField(max_length=255, blank=True, default='')
    date        = models.DateField(blank=True, null=True, help_text="Events without dates aren't displayed, except if recurring.")
    time        = models.TimeField(blank=True, null=True,
                                   help_text="24 HOUR TIME. Add a usual time for recurring events. This will be over-ridden if specific time added.")

    expires = models.DateField(blank=True, null=True, help_text="Optional.")

    paypal = models.CharField(max_length=65, blank=True, default='',
                              help_text="Paypal provided hosted_button_id")
    door_cost   = models.CharField(max_length=255, blank=True, default='', verbose_name='cost')
    ticket_url  = models.URLField(blank=True, default='',
        help_text="External ticket URL (if applicable)")
    gig_details = models.TextField(max_length=999, verbose_name="Snippet Text",
        help_text="Short text. LIMITED TO 175 words.")
    content = models.TextField(blank=True, default='',
        help_text="More artist info / bio.")
    extra_URLs  = models.TextField(blank=True, default='',
        help_text="eg. artist Myspace / website, separate multiple urls  with commas.")
    post_event_gallery = models.ForeignKey(Gallery, blank=True, null=True)

    extra_images = models.ManyToManyField(
        Photo, blank=True,
    )

    twitter_account = models.CharField(max_length=100, blank=True, default='')
    facebook_event = models.CharField(max_length=255, blank=True, default='')

    tags = TaggableManager(blank=True)

    objects = querysets.QuerySet.as_manager()

    def save(self):
        self.slug = slugify(self.event_name)
        if self.spotlight and not self.spotlight_order:
            self.spotlight_order = '999'

        ## set event_image (hidden field with absolute version)
        if not self.event_image:
            if self.main_image:
                self.event_image = self.main_image
            elif self.poster:
                self.event_image = self.poster
            else:
                pass

        super(Event, self).save()
        ## handle date object: ~ add if not || ~ correct image
        e = EventDate.objects.filter(event=self) #, date=self.date)
        if e:
            today = datetime.datetime.today()
            d = e.filter(date__gte=today)
            if d:
                c = d.order_by('date')[0]
                self.date = c.date
                if c.date_image:
                    self.event_image = c.date_image
        else:
            e = EventDate(event=self, date=self.date)
            e.save()
        super(Event, self).save()

    def __str__(self):
        return self.event_name


    class Meta:
        ordering = ['-date', '-recurring']


class EventDate(models.Model):
    event = models.ForeignKey(Event)
    date  = models.DateField()
    time  = models.TimeField(blank=True, null=True)
    additional = models.CharField(max_length=999, blank=True,
                                  default='', help_text="Make it special.")
    date_image  = models.ForeignKey(
        Photo,
        blank=True, null=True,
        related_name="date_image",
        )

    def __unicode__(self):
        return '%s -- %s' % (self.date, self.event.event_name)


    class Meta:
        ordering = ['-date']


class EventGallery(models.Model):
    event = models.ForeignKey(Event)
    photo = models.ForeignKey(Photo)
    order = models.IntegerField(default=0)

    def __unicode__(self):
        return self.event.event_name


class EventVideo(models.Model):
    event = models.ForeignKey(Event)
    video = models.CharField(max_length=255,
                             verbose_name="Youtube video",
                             help_text="YouTube video link.")
    order = models.IntegerField(default=0)

    ## s.find('v=').split('&')[0]
    ## http://www.youtube.com/watch?v=3I6jWE5UIYg&feature=related

    def save(self):
        if not self.order:
            self.order = '999'
        v = self.video
        if v[:4] == 'http':
            self.video = v[v.find('v=')+2:].split('&')[0]
            #"http://www.youtube.com/v/%s&hl=en&fs=1" % v
        super(EventVideo, self).save()

    def __unicode__(self):
        return '%s -- %s' % (self.event.event_name, self.video)

    class Meta:
        ordering = ['order']


class EventUser(models.Model):
    event = models.ForeignKey(Event)
    user = models.ForeignKey(User, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=255, blank=True, default='')
    number_tickets = models.IntegerField(null=True)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    def save(self):
        if not self.order:
            self.order = '999'
        super(ComingEvent, self).save()

    class Meta:
        ordering = ['event']

project/events/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from .models import Event, EventUser
from django import forms
from tinymce.widgets import TinyMCE


class EventAdminForm(forms.ModelForm):

    class Meta(object):
        exclude = []
        model = Event
        widgets = {'content': TinyMCE()}


class EventUserForm(forms.ModelForm):
    model = EventUser

project/events/views.py
import datetime
from django.shortcuts import render_to_response, redirect#, get_object_or_404, get_list_or_404
from django.template import RequestContext
from .models import Event, EventDate


def home(request, context={}, template='home.html'):
    ## spotlight
    today = datetime.datetime.today()-datetime.timedelta(days=1)
    spotlight = Event.objects.filter(spotlight=True).order_by('?')
    if spotlight.filter(date__gte=today):
        context['spotlights'] = spotlight.filter(date__gte=today)
    else:
        context['spotlights'] = spotlight[:4]
    context['events'] = Event.objects.filter(spotlight=False, recurring=False, date__gte=today).order_by('date')[:4]
    context['year'] = today.year
    return render_to_response(template, context_instance=RequestContext(request, context))


def entertainment(request, context={}, template='events/entertainment.html'):
    today = datetime.datetime.today()

    spotlight = Event.objects.filter(spotlight=True).order_by('?')
    if spotlight.filter(date__gte=today):
        context['spotlights'] = spotlight.filter(date__gte=today)
    else:
        context['spotlights'] = spotlight[:4]

    events = Event.objects.filter(spotlight=False, recurring=False, date__gte=today).order_by('?')
    context['entertains'] = entertains = events.filter(poster__pk__gt=0)[:2]

    ## the following upsets me
    context['events'] = events.exclude(id__in=[o.id for o in entertains])[:2]


    context['year'] = today.year
    #month_events = EventDate.objects.filter(date__month=today.month, date__year=today.year).order_by('date')
    next_month = today + datetime.timedelta(days=45)
    month_events = EventDate.objects.filter(date__gte=today, date__lte=next_month).order_by('date')
    context['month_events'] = month_events
    context['month_text'] = today
    return render_to_response(template, context_instance=RequestContext(request, context))


def check_update_date(event):
    if event.eventdate_set.count()>1:
        today = datetime.datetime.today()-datetime.timedelta(days=1)
        check = event.eventdate_set.filter(date__gte=today).order_by('date')
        if check:
            check = check[0]
            if event.date < check.date:
                event.date = check.date
                event.save()


def event_recur(request, id, slug, context={}, template='events/event.html'):
    ## event = get_object_or_404(Event, slug=slug, recurring=True)
    context['event'] = event = Event.objects.get(pk=id)#, recurring=True)
    try:
        context['recur'] = EventDate.objects.get(event=event, date=event.date)
    except:
        pass
    context['current_path'] = request.get_full_path()
    check_update_date(event)
    return render_to_response(template, context_instance=RequestContext(request, context))


def event_day(request, year, month, day, context={}, template='events/events.html'):
    day = datetime.date(year=int(year), month=int(month), day=int(day))
    context['events'] = event = Event.objects.filter(eventdate__date=day)
    ##context['day'] = True
    return render_to_response(template, context_instance=RequestContext(request, context))


def event_detail(request, year, month, day, slug, context={}, template='events/event.html'):
    day = datetime.date(year=int(year), month=int(month), day=int(day))
    context['event_detail'] = True
    try:
        event = Event.objects.filter(eventdate__date=day, slug=slug)[0]
    except:
        return redirect('/404/')
    if event.recurring:
        return redirect('/events/regular/%s/%s/' % (event.pk, event.slug))
    context['event'] = event
    context['current_path'] = request.get_full_path()
    check_update_date(event)
    return render_to_response(template, context_instance=RequestContext(request, context))

templates/events/base.html
{% extends "base.html" %}

templates/events/entertainment.html
{% extends 'base.html' %}

{% block head_end %}
{% include 'include_spotlight_js.html' %}
<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.lightbox-0.5.js"></script>
<script type="text/javascript">
$(function() {$('.poster').lightBox();});
</script>
{% endblock %}

{% block content %}
<table cellpadding="0" cellspacing="0" style="border:0; padding:0; margin:0;">  
{% include 'include_spotlight_td.html' %}
{% include 'include_events.html' %}
<tr>
    <td valign="top">
<p><br /></p>
<h1 class="centre white">
    TRANSIT<br />
    UPCOMING GIGS{#month_text|date:"F Y"|upper#}<br />
    CALENDAR
</h1>
<p>
{% for event in month_events %}
<div class="centre white" style="font-size:10px; {% if event.event.pk == 17 %}margin-top:10px;{% endif %}">
    <a class="white" href="/events/{{event.event.date|date:'Y/m/d/'}}">{{event.date|date:"D j F"}}: </a>
    <a class="white" href="/events/{{event.event.date|date:'Y/m/d/'}}{{event.event.slug}}/">{{event.event.event_name|safe}}</a>
</div>
{% endfor %}
</p>
    </td>

    <td valign="top">
<p><br /></p>
<p><br /></p>
{% for event in entertains %}
<a class="poster" href="/media/{{event.poster.image}}" title="{{event.event_name}} //">
    <img width="280px" style="padding: 0 10px 10px 10px;" src="{{MEDIA_URL}}{{event.poster.image}}" alt="{{event}}" align="right" />
{% endfor %}
    </td>
</tr>

</table>
{% endblock %}

templates/events/event.html
{% extends 'base.html' %}

{% block title %}
{{event.event_name}} // {{event.time|time:"fA"}} {{event.date|date:"l"}} {{event.date|date:"j F Y"}}
{% endblock %}

{% block head_end %}
<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.lightbox-0.5.js"></script>
<script type="text/javascript">
$(function() {$('#gallery a, #poster').lightBox();});
var disqus_developer = 1;
</script>
{% endblock %}

{% block content %}
<table id="event" cellpadding="0" cellspacing="0" style="border:0; padding:0; margin:0;">  
    {# --------------------- SPOTLIGHT --------------------- #}
    <tr>
        <td class="block_dark" valign="top" colspan="2">
{% include 'include_spotlight.html' %}
        </td>
    </tr>
    <tr><td colspan="2"><br />{{check}}</td></tr>
    <tr>
		<td valign="top">
{# -- youtube vids -- #}
{% for video in event.eventvideo_set.all %}
<object width="325" height="260" style="margin: 0;">
<param value="http://www.youtube.com/v/{{video.video}}&hl=en&fs=1" name="movie"></param>
<param name="allowFullScreen" value="true"></param>
<param name="allowscriptaccess" value="always"></param>
<param name="wmode" value="transparent" /></param>
<embed src="http://www.youtube.com/v/{{video.video}}&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="325" height="260"></embed>
</object><br /><br />
{% endfor %}

{# -- comments -- #}
{% include 'events/extract_fb_like.html' %}
{% include 'events/extract_disqus.html' %}
        </td>
        <td width="300" valign="top">
{# -- text details -- #}
<div style="padding: 0 15px 0 25px;">
    <p> {% if event.extra_details %}{{event.extra_details|safe}}{% endif %}                  
        {% if event.extra_URLs %}<br /><div style="text-transform: uppercase; font-weight: bold;">{{event.extra_URLs|safe|urlize}}</div>{% endif %}

    <h2>{% if event.door_cost %}<br />+{{event.door_cost|upper}}{% endif %}
        {% if event.ticket_url %}<br /><a target="_blank" href="{{event.ticket_url}}">+BUY TICKETS</a>{% endif %}
    </h2>
<br />
{% if event.twitter_account %}
{% include 'events/extract_twitter.html' %}
{% endif %}
</p>
</div>	


{# -- mini-gallery -- #}
<div id="gallery" class="event" style="margin: 0 8px 0 12px;">
{% for thumb in event.post_event_gallery.photos.all %}
    <a href="/media/{{thumb.image}}" title="{{event.event_name}} {{thumb.caption}} //">
<img class="thumb" src="{{thumb.get_gallery_thumb_url}}" style="padding:0 {% cycle '5px' '5px' '0'  %} 5px 0;" border="0" />
    </a>
{% endfor %}

</div>

        </td>
    </tr>
</table>
{% endblock %}


templates/events/eventdate_list.html
{% extends "events/base.html" %}

{% block title %}Events - {{ block.super }}{% endblock %}


{% block content %}

<h1>Events</h1>

{% for event in object_list %}
  <p>{{ event }}</p>
{% endfor %}

{% endblock %}

templates/events/events.html
{% extends 'base.html' %}

{% block content %}
<table cellpadding="0" cellspacing="0" style="border:0; padding:0; margin:0;">  
{% for event in events %}
    <tr>
        <td class="{% cycle 'block_reda' 'block_dark' %}" valign="top">
    {% include 'include_spotlight.html' %}
        </td>
    </tr>
{% endfor %}
</table>
{% endblock %}

templates/events/eventuser_detail.html
{% extends 'base.html' %}

{% block title %}
{{event.event_name}} // {{event.time|time:"fA"}} {{event.date|date:"l"}} {{event.date|date:"j F Y"}}
{% endblock %}


{% block content %}


{% endblock %}

templates/events/extract_disqus.html
<style type="text/css">
/*
#disqus_thread h3 {font-size: 11px;}
*/
div#dsq-reply, div.dsq-textarea-wrapper, 
select#dsq-sort-select {font-size:10px;}
div.dsq-textarea-wrapper {min-height: 90px; padding: 3px; background: #500000;} /*5d3434*/
#dsq-content #dsq-global-toolbar .dsq-toolbar-item,
#dsq-content .dsq-avatar img, div.dsq-textarea-background, #dsq-reply .dsq-post-tools {
border: 0; box-shadow: 0; -moz-box-shadow: 0; -webkit-box-shadow: 0;
border-radius: 0; -moz-border-radius: 0; -webkit-border-radius: 0;}
#dsq-content #dsq-global-toolbar .dsq-toolbar-item {margin: 0; height: 20px; background-position-y: -1px;}
#dsq-content .dsq-avatar img {width: 36px; height: 36px;}
#dsq-content #dsq-toolbar-dropdown #dsq-toolbar-dropdown-wrap {
-moz-border-radius: 0; -webkit-border-radius: 0;
height: 18px; background: #330000; background-position-y: -2px; z-index: 1000;}
div.dsq-comment-header {background: #330000; padding: 3px 5px 5px 5px; margin: 5px 0; border: none;}
.dsq-post-tools .dsq-post-as .dsq-button, button.dsq-button, 
.dsq-post-tools .dsq-post-as .dsq-button, button.dsq-button:hover, 
button.dsq-button-small {line-height: 14px; color: #aaa; margin: 0 1px 0 2px;padding: 6px 10px 4px 10px; 
border: none; background: #330000; text-shadow: none; box-shadow: 0; -moz-box-shadow: 0; -webkit-box-shadow: 0;
border-radius: 0; -moz-border-radius: 0; -webkit-border-radius: 0;font-size: 10px; font-weight: normal; height: 25px;}
span.dsq-commenter-name {font-size: 11px; color: #eee;}
#dsq-content .dsq-show-tools .dsq-post-tools {
display: block;height: 24px;padding: 0 5px;}
button.dsq-button:hover{ background: #999; }
.dsq-comment-body {padding: 0 0 0 42px;}
div#dsq-global-toolbar, #disqus_thread h3, table.dsq-global-toolbar-container,
div.dsq-community-preview, div#dsq-sort-by{ visibility:hidden; display:none;}
div#dsq-popup-message.dsp-popup.dsp-popup-message.dsp-login-box {position: relative!important; top: 0; left: 300px;}
div#dsq-popup-message.dsp-popup.dsp-popup-message {position: relative!important; top: 0; left: 300px;}
ul#dsq-footer {display: none;}
div.dsq-popup-container {left: 80%;}
/**/
</style>
<div id="disqus_thread" style="font-size: 10px; margin: 10px 0 0 10px;"></div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>	
<script type="text/javascript">
    var disqus_shortname = 'transitbar';
    var disqus_url = 'http://transitbar.com.au{{current_path}}';
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>



templates/events/extract_fb_like.html
<script src="http://connect.facebook.net/en_US/all.js#appId=220817504602860&amp;xfbml=1"></script>
<fb:like style="margin-left: 10px;" href="{{ request.build_absolute_uri }}" send="false" layout="button_count" width="150" show_faces="true" font="arial"></fb:like>
<div class="fb_like"><div id="fb-root"></div></div>

<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4dfed48b58927ce5"></script>
<script type="text/javascript">/* var addthis_config = {ui_offset_top: 0} */
var addthis_config = {ui_offset_left: 200}
</script>
<style type="text/css">
#at16p {margin-top: 0; margin-left: 120px;}
</style>

<div class="addthis_toolbox addthis_default_style "
       addthis:url="{{ request.build_absolute_uri }}"
       addthis:title="{{event.event_name}}"
       style="float: right; margin-top: -19px; margin-right: -2px;">
 <a class="addthis_button_email"></a>
 <a class="addthis_button_twitter"></a>
 <a class="addthis_button_google"></a>
 <a class="addthis_button_compact"></a>
</div>

templates/events/recur_event.html
{% if recur.additional %}<p>***<br /><strong>{{recur.additional}}</strong></p><p>***</p>{% endif %}